name: Build OpenWrt system image (Stable 5.15)

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: false
        default: "immortalwrt_master"
        type: choice
        options:
          - immortalwrt_master
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "5.15.y"
        type: choice
        options:
          - 5.15.y
          - 6.1.y
          - 6.6.y
      openwrt_ip:
        description: "Set OpenWrt default IP address."
        required: false
        default: "192.168.1.1"

env:
  # مسارات الإعدادات بناءً على اختيارك للفرع
  CONFIG_FILE: config/${{ inputs.source_branch }}/config
  DIY_P2_SH: config/${{ inputs.source_branch }}/diy-part2.sh
  TZ: Etc/UTC

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Initialize Environment
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-make-openwrt-depends)
          sudo mkdir -p /builder
          sudo chown -R runner:runner /builder

      - name: Clone Source
        working-directory: /builder
        run: |
          # سيقوم بجلب الماستر دائماً لضمان الاستقرار
          git clone -q --single-branch --depth=1 --branch=master https://github.com/immortalwrt/immortalwrt openwrt

      - name: Update Feeds
        run: |
          cd /builder/openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Config & DIY
        run: |
          [ -e "${{ github.workspace }}/${CONFIG_FILE}" ] && cp -f ${{ github.workspace }}/${CONFIG_FILE} /builder/openwrt/.config
          chmod +x ${{ github.workspace }}/${DIY_P2_SH}
          cd /builder/openwrt
          # نمرر الأي بي المختار من الواجهة للسكريبت
          ${{ github.workspace }}/${DIY_P2_SH} "${{ inputs.openwrt_ip }}"

      - name: Compile
        id: compile
        run: |
          cd /builder/openwrt
          make defconfig
          make -j$(nproc) || make -j1 V=s
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Package for Beelink GT1 Mini
        if: ${{ steps.compile.outputs.status == 'success' }}
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: /builder/openwrt/bin/targets/*/*/*rootfs.tar.gz
          openwrt_board: s905x2
          # نستخدم النواة المختارة من القائمة (يفضل 5.15 حالياً)
          openwrt_kernel: ${{ inputs.openwrt_kernel }}
          auto_kernel: false
